trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: azureResourceManagerConnection
    value: BicepAVDSC

stages:
  - template: ../SessionHosts.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      location: 'westeurope'
      resourceGroupName: 'rg-avd-pl-bicep-test'
      subscriptionName: 'Visual Studio Enterprise Subscription – MPN'
      stage: SessionHosts